# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dlgwas',
                'doc_host': 'https://DanielKick-USDA.github.io',
                'git_url': 'https://github.com/DanielKick-USDA/dlgwas',
                'lib_path': 'dlgwas'},
  'syms': {'dlgwas.core': {'dlgwas.core.foo': ('core.html#foo', 'dlgwas/core.py')}}}
