# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_zma_parse_other.ipynb.

# %% auto 0
__all__ = ['read_txt', 'print_txt', 'taxa_to_filename', 'get_AGPv4']

# %% ../nbs/02_zma_parse_other.ipynb 9
def read_txt(path, 
             **kwargs # Intended to allow for explicit 'encoding' to be passed into open the file
            ):
    if 'encoding' in kwargs.keys():
        print(kwargs)
        with open(path, 'r', encoding  = kwargs['encoding']) as f:
            data = f.read()        
    else:    
        with open(path, 'r') as f:
            data = f.read()
            
    return(data)

# %% ../nbs/02_zma_parse_other.ipynb 10
def print_txt(path):
    print(read_txt(path = path))

# %% ../nbs/02_zma_parse_other.ipynb 20
def taxa_to_filename(taxa = '05-397:250007467'): return(taxa.replace(':', '__'))

taxa_to_filename(taxa = '05-397:250007467')

# %% ../nbs/02_zma_parse_other.ipynb 21
def get_AGPv4( 
    taxa,
    table_directory = '../data/zma/panzea/genotypes/GBS/v27/ZeaGBSv27_publicSamples_imputedV5_AGPv4-181023_Table/'
):
    with open(table_directory+taxa, 'r') as f:
        data = f.read()    
    data = data.split('\t')
    return(data)

get_AGPv4('05-397__250007467')[0:4]
