# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09_Deep_Learning_Convenience_Functions.ipynb.

# %% auto 0
__all__ = ['calc_cs', 'apply_cs', 'reverse_cs']

# %% ../nbs/09_Deep_Learning_Convenience_Functions.ipynb 3
def calc_cs(x # numeric array
           ): 
    "Calculate nan mean and nan std of an array. Returned as list"
    import numpy as np
    return [np.nanmean(x, axis = 0), np.nanstd(x, axis = 0)]

# %% ../nbs/09_Deep_Learning_Convenience_Functions.ipynb 4
def apply_cs(xs, 
             cs_dict_entry # list of length 2 containing mean and s
            ): return ((xs - cs_dict_entry[0]) / cs_dict_entry[1])

# %% ../nbs/09_Deep_Learning_Convenience_Functions.ipynb 5
def reverse_cs(xs, cs_dict_entry): return (cs_dict_entry[1] * xs) + cs_dict_entry[0]
